Update

diff --git a/jigs/ubuntu/update_discord b/jigs/ubuntu/update_discord
--- a/jigs/ubuntu/update_discord
+++ b/jigs/ubuntu/update_discord
@@ -1,6 +1,13 @@
 #!/usr/bin/env bash
+set -euo pipefail
 
-pushd ~/Downloads/
-deb=$(ls -t discord*.deb | head -n 1)
-sudo dpkg -i $deb
-popd
+deb=~/Downloads/discord.deb
+
+wget -O "$deb" "https://discord.com/api/download/stable?platform=linux&format=deb"
+
+if [ -f "$deb" ]; then
+    sudo dpkg -i "$deb"
+    rm "$deb"
+else
+    echo "Failed to download Discord."
+fi
